# Sentiment Analysis

### Importing dependencies

In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
import nltk
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords

In [3]:
from sklearn.feature_extraction.text import CountVectorizer

In [4]:
import pickle

### Reading the dataset

In [5]:
review = pd.read_csv('IMDB Dataset.csv')
review.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [6]:
review=review.sample(10000)

### Preprocessing

In [7]:
review['sentiment'].replace({'positive':1,"negative":0},inplace=True)

In [8]:
review.loc[review['sentiment']==1]

review  sentiment
28000  Out of all the Mafia movies i have ever seen t...          1
41622  Vertigo co-stars Stewart (in his last turn as ...          1
16411  Gary Busey is the title character, Frank "Bull...          1
10145  I would not hesitate to put this adaptation of...          1
9745   Yes, this is one of the great musical movies I...          1
...                                                  ...        ...
29688  <br /><br />I take issue with the other review...          1
29929  BASEketball is one of the funniest movies I ha...          1
22580  Antarctica, winter 1982. The team on an Americ...          1
39164  Taking a break from his escapist run in the ea...          1
9947   One of the best movies out there. Yeah maybe t...          1

[5017 rows x 2 columns]

In [9]:
review['review']

2024     I liked the understated character that Laura L...
28000    Out of all the Mafia movies i have ever seen t...
41622    Vertigo co-stars Stewart (in his last turn as ...
16411    Gary Busey is the title character, Frank "Bull...
10145    I would not hesitate to put this adaptation of...
                               ...                        
39164    Taking a break from his escapist run in the ea...
10024    Painful. Painful is the only word to describe ...
9947     One of the best movies out there. Yeah maybe t...
27240    Elephants Dream was supposed to be the flagshi...
35922    I had this movie given to me, and have to admi...
Name: review, Length: 10000, dtype: object

In [10]:
review['review'].replace("<br />","",regex=True, inplace=True)
review['review'].replace("[^a-zA-Z]"," ",regex=True, inplace=True)

In [11]:
review

review  sentiment
2024   I liked the understated character that Laura L...          0
28000  Out of all the Mafia movies i have ever seen t...          1
41622  Vertigo co stars Stewart  in his last turn as ...          1
16411  Gary Busey is the title character  Frank  Bull...          1
10145  I would not hesitate to put this adaptation of...          1
...                                                  ...        ...
39164  Taking a break from his escapist run in the ea...          1
10024  Painful  Painful is the only word to describe ...          0
9947   One of the best movies out there  Yeah maybe t...          1
27240  Elephants Dream was supposed to be the flagshi...          0
35922  I had this movie given to me  and have to admi...          0

[10000 rows x 2 columns]

In [12]:
review['review'] = review['review'].apply(lambda x: " ".join(x.lower() for x in x.split()))
stop = stopwords.words('english')
review['review'] = review['review'].apply(lambda x: " ".join(x for x in x.split() if x not in stop))

In [13]:
review

review  sentiment
2024   liked understated character laura linney playe...          0
28000  mafia movies ever seen one best many reasons a...          1
41622  vertigo co stars stewart last turn romantic le...          1
16411  gary busey title character frank bulletproof m...          1
10145  would hesitate put adaptation death trap top l...          1
...                                                  ...        ...
39164  taking break escapist run early steven spielbe...          1
10024  painful painful word describe awful rendition ...          0
9947   one best movies yeah maybe cinematography grea...          1
27240  elephants dream supposed flagship project open...          0
35922  movie given admit glad pay money back box make...          0

[10000 rows x 2 columns]

In [14]:
ps = PorterStemmer()

In [15]:
corpus = []
for i in review["review"]:
    temp = i
    temp = temp.split()
    temp = [ps.stem(word) for word in temp]
    temp = ' '.join(temp)
    corpus.append(temp)

In [16]:
review["review"] = corpus

In [17]:
review

review  sentiment
2024   like underst charact laura linney play love ac...          0
28000  mafia movi ever seen one best mani reason act ...          1
41622  vertigo co star stewart last turn romant lead ...          1
16411  gari busey titl charact frank bulletproof mcba...          1
10145  would hesit put adapt death trap top list best...          1
...                                                  ...        ...
39164  take break escapist run earli steven spielberg...          1
10024  pain pain word describ aw rendit fun interest ...          0
9947   one best movi yeah mayb cinematographi greates...          1
27240  eleph dream suppos flagship project open sourc...          0
35922  movi given admit glad pay money back box make ...          0

[10000 rows x 2 columns]

### Creating the bag of words

In [18]:
countvector=CountVectorizer()

In [19]:
X=countvector.fit_transform(review['review']).toarray()

In [20]:
pickle.dump(countvector,open('bag.pkl','wb'))

In [21]:
X[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [22]:
type(X)

numpy.ndarray

In [23]:
X.shape
y=review.iloc[:,-1].values
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

### Model using Gaussian Naive Bayes

In [24]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X_train,y_train)

GaussianNB()

In [25]:
pickle.dump(model,open('model.pkl','wb'))

In [23]:
y_predict=model.predict(X_test)

In [24]:
predicted = model.predict(X[1].reshape(1, -1))

In [25]:
predicted

array([0], dtype=int64)

In [26]:
if predicted == 0:
    print("Negative")
else:
    print("Positive")

Negative


In [27]:
import pickle

In [28]:
pickle.dump(model,open('model.pkl','wb'))

In [37]:
pickle.dump(countvector,open('bag.pkl','wb'))

In [36]:
content = "This is a good movie, I liked it very much loved it. Would really recommend the movie."
# data = [content]
vect = bag.transform(content).toarray()
prediction = model.predict(data.toarray().reshape(1, -1))

NameError: name 'bag' is not defined

In [35]:
X[1]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)